/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsDate,
  IsString,
  ValidateNested,
  IsOptional,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { Message } from "../../message/base/Message";
import { EnumBotPlatform } from "./EnumBotPlatform";
import { ScrapingBot } from "../../scrapingBot/base/ScrapingBot";
import { User } from "../../user/base/User";

@ObjectType()
class Bot {
  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: () => [Message],
  })
  @ValidateNested()
  @Type(() => Message)
  @IsOptional()
  messages?: Array<Message>;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name!: string | null;

  @ApiProperty({
    required: false,
    enum: EnumBotPlatform,
  })
  @IsEnum(EnumBotPlatform)
  @IsOptional()
  @Field(() => EnumBotPlatform, {
    nullable: true,
  })
  platform?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: () => [ScrapingBot],
  })
  @ValidateNested()
  @Type(() => ScrapingBot)
  @IsOptional()
  scrapingBots?: Array<ScrapingBot>;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;

  @ApiProperty({
    required: false,
    type: () => User,
  })
  @ValidateNested()
  @Type(() => User)
  @IsOptional()
  user?: User | null;
}

export { Bot as Bot };
