/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested, IsEnum } from "class-validator";
import { MessageListRelationFilter } from "../../message/base/MessageListRelationFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { EnumBotPlatform } from "./EnumBotPlatform";
import { ScrapingBotListRelationFilter } from "../../scrapingBot/base/ScrapingBotListRelationFilter";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class BotWhereInput {
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => MessageListRelationFilter,
  })
  @ValidateNested()
  @Type(() => MessageListRelationFilter)
  @IsOptional()
  @Field(() => MessageListRelationFilter, {
    nullable: true,
  })
  messages?: MessageListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    enum: EnumBotPlatform,
  })
  @IsEnum(EnumBotPlatform)
  @IsOptional()
  @Field(() => EnumBotPlatform, {
    nullable: true,
  })
  platform?: "Option1";

  @ApiProperty({
    required: false,
    type: () => ScrapingBotListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ScrapingBotListRelationFilter)
  @IsOptional()
  @Field(() => ScrapingBotListRelationFilter, {
    nullable: true,
  })
  scrapingBots?: ScrapingBotListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput;
}

export { BotWhereInput as BotWhereInput };
